### 과제 9

#1

In [13]:
import numpy as np
scores_list = [88, 92, 79, 95,
          75, 68, 82, 70,
          92, 99, 95, 88,
          60, 72, 65, 58,
          85, 80, 78, 90]
#1
print('1번 문제:')
scores = np.array(scores_list).reshape(5, 4)
print(f'shape: {scores.shape}')
print(f'ndim: {scores.ndim}')
print(f'size: {scores.size}')
print(f'dtype: {scores.dtype}\n')

#2
print('2번 문제:')
student_means = np.mean(scores, axis=1)
subject_means = np.mean(scores, axis=0)
print(f'학생 별 평균: {student_means}')
print(f'과목 별 평균: {subject_means}\n')

#3
print('3번 문제:')
pos = np.argmax(scores)
max_score = np.max(scores)
row = pos // 4
col = pos % 4
print(f'최고 점수: {max_score}')
print(f'1차원 인덱스 위치: {pos}')
print(f'2차원 인덱스 (행, 열): ({row}, {col}) -> {row + 1}번째 학생, {col + 1}번째 과목\n')

#4
print('4번 문제:')
total_mean = np.mean(scores)
total_std = np.std(scores)
total_var = np.var(scores)

print(f'전체 평균: {total_mean}')
print(f'전체 표준편차: {total_std:.2f}')
print(f'전체 분산: {total_var:.2f}\n')

#5
print('5번 문제:')
mask = student_means >= 80
indices = np.where(mask)[0]
count = np.sum(mask)

print(f"평균 80점 이상 학생 인덱스: {indices}")
print(f"평균 80점 이상 인원수: {count}명")
print("해당 학생들의 성적:\n", scores[mask], "\n")


1번 문제:
shape: (5, 4)
ndim: 2
size: 20
dtype: int64

2번 문제:
학생 별 평균: [88.5  73.75 93.5  63.75 83.25]
과목 별 평균: [80.  82.2 79.8 80.2]

3번 문제:
최고 점수: 99
1차원 인덱스 위치: 9
2차원 인덱스 (행, 열): (2, 1) -> 3번째 학생, 2번째 과목

4번 문제:
전체 평균: 80.55
전체 표준편차: 11.83
전체 분산: 139.85

5번 문제:
평균 80점 이상 학생 인덱스: [0 2 4]
평균 80점 이상 인원수: 3명
해당 학생들의 성적:
 [[88 92 79 95]
 [92 99 95 88]
 [85 80 78 90]] 



In [ ]:
#6
print('6번 문제:')
count_90_above = np.sum(scores >= 90)
any_100 = np.any(scores >= 100)
all_60_above = np.all(scores >= 60)

print(f'90점 이상인 점수의 개수: {count_90_above}개')
print(f'100점 이상인 점수 여부: {any_100}')
print(f'모든 점수가 60점 이상 여부: {all_60_above}\n')

#7
print('7번 문제:')
grades = np.where(scores >= 90, 'A', np.where(scores >= 80, 'B', 'C'))
print('등급 배열:\n', grades)

6번 문제:
90점 이상인 점수의 개수: 6개
100점 이상인 점수 여부: False
모든 점수가 60점 이상 여부: False

7번 문제:
등급 배열:
 [['B' 'A' 'C' 'A']
 ['C' 'C' 'B' 'C']
 ['A' 'A' 'A' 'B']
 ['C' 'C' 'C' 'C']
 ['B' 'B' 'C' 'A']]


#2

In [ ]:
np.random.seed(2024)
img = np.random.randint(0, 256, size=(8, 8))

#1
print('1번 문제:')
print(img, '\n')

#2
print('2번 문제:')
print(img[2:6, 2:6], '\n')

#3
print('3번 문제:')
print(img[::2], '\n')

1번 문제:
[[136 250  96 128  27  36 190 183]
 [ 41 127 193  60 227  74  66 224]
 [165 252 241 158 111 247 202 110]
 [ 95 111  11  28  91  39  54 114]
 [183  73 102 218 244  42  31  97]
 [150  27  86 119  69 157  61 243]
 [ 54 132  57  86  54 254 148 126]
 [136  18  97  90 202 135 176 232]] 

2번 문제:
[[241 158 111 247]
 [ 11  28  91  39]
 [102 218 244  42]
 [ 86 119  69 157]] 

3번 문제:
[[136 250  96 128  27  36 190 183]
 [165 252 241 158 111 247 202 110]
 [183  73 102 218 244  42  31  97]
 [ 54 132  57  86  54 254 148 126]] 



In [33]:
#4
print('4번 문제:')
bin_img = np.where(img >= 128, 255, 0)
print(bin_img, '\n')

#5
print('5번 문제:')
white_count = np.sum(bin_img == 255)
black_count = np.sum(bin_img == 0)
print(f'흰색 픽셀 개수: {white_count}개')
print(f'검은색 픽셀 개수: {black_count}개\n')

4번 문제:
[[255 255   0 255   0   0 255 255]
 [  0   0 255   0 255   0   0 255]
 [255 255 255 255   0 255 255   0]
 [  0   0   0   0   0   0   0   0]
 [255   0   0 255 255   0   0   0]
 [255   0   0   0   0 255   0 255]
 [  0 255   0   0   0 255 255   0]
 [255   0   0   0 255 255 255 255]] 

5번 문제:
흰색 픽셀 개수: 28개
검은색 픽셀 개수: 36개



In [35]:
#6
print('6번 문제:')
left, right = np.split(img, 2, axis=1)
print('좌측 절반:\n', left)
print('우측 절반:\n', right, '\n')

6번 문제:
좌측 절반:
 [[136 250  96 128]
 [ 41 127 193  60]
 [165 252 241 158]
 [ 95 111  11  28]
 [183  73 102 218]
 [150  27  86 119]
 [ 54 132  57  86]
 [136  18  97  90]]
우측 절반:
 [[ 27  36 190 183]
 [227  74  66 224]
 [111 247 202 110]
 [ 91  39  54 114]
 [244  42  31  97]
 [ 69 157  61 243]
 [ 54 254 148 126]
 [202 135 176 232]] 



In [44]:
#7
print('7번 문제:')
merged = np.concatenate([right, left], axis=1)
print(merged, '\n')

#8
print('8번 문제:')
flat = img.ravel()
print(f'앞 10개 값: {flat[:10]}')
print(f'shape: {flat.shape}\n')
#9
print('9번 문제:')
pick = img[img >= 128]
print(f'128 이상 픽셀 개수: {pick.size}')
print(f'128 이상 픽셀 평균: {np.mean(pick):.2f}')

7번 문제:
[[ 27  36 190 183 136 250  96 128]
 [227  74  66 224  41 127 193  60]
 [111 247 202 110 165 252 241 158]
 [ 91  39  54 114  95 111  11  28]
 [244  42  31  97 183  73 102 218]
 [ 69 157  61 243 150  27  86 119]
 [ 54 254 148 126  54 132  57  86]
 [202 135 176 232 136  18  97  90]] 

8번 문제:
앞 10개 값: [136 250  96 128  27  36 190 183  41 127]
shape: (64,)

9번 문제:
128 이상 픽셀 개수: 28
128 이상 픽셀 평균: 193.07


#3

In [48]:
sales = np.array([[120,  80,  45,  60],
                  [200, 150,  90,  30],
                  [ 75,  60, 120,  95]])
price = np.array([1500, 3000, 5000, 2000])

# 1. 브로드캐스트 적용
revenue_matrix = sales * price
print('1. 브로드캐스트를 적용한 제품별 매출액:\n', revenue_matrix, '\n')
branch_total_sum = np.sum(revenue_matrix, axis=1)
print(branch_total_sum, '\n')

# 2. 행렬 연산(행렬곱) 적용
branch_total = sales.dot(price)
print('2. 행렬 연산을 적용한 지점별 총 매출액:\n', branch_total)

1. 브로드캐스트를 적용한 제품별 매출액:
 [[180000 240000 225000 120000]
 [300000 450000 450000  60000]
 [112500 180000 600000 190000]] 

[ 765000 1260000 1082500] 

2. 행렬 연산을 적용한 지점별 총 매출액:
 [ 765000 1260000 1082500]
